name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby_version: ["2.7", "3.1", "3.2"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}

      - name: Install dependencies
        run: |
          gem install bundler
          gem install minitest

      - name: Run tests
        run: ruby test_exline.rb
